### ISSUE TITLE
Looking at the 2nd page of the book and quill in Isa's mailbox will consistently cause a game crash.

### ISSUE THREAD

**Issue by 0sp** [rDankMemes/Minecraft-Server-Support#24]
(This is not a joke. I am 100% serious.)

**Describe the bug**
Looking at the 2nd page of the book and quill in Isa's mailbox will cause a game crash.

**To Reproduce**
1. Go to Isa's house
2. Take the book out of the mailbox and go to page 2
3. Game crash

**Expected behavior**
I should be able to see "I fuck cans of ravioli -ChemistryPony" on the book.

**Screenshots**

**Your Environment**
 - Client Version: 1.15.2
 - OS: Mint
 - Mods or Shaders: OptiFine

**Additional context**
What actually happens:

- "Saving world" screen occurs even though we are on a server
- Game crash
- Exit with IndexOutOfBoundsException

The game crashed whilst rendering screen
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: 49

java.lang.StringIndexOutOfBoundsException: String index out of range: 49
	at java.lang.String.substring(String.java:1951)
	at dha.m(SourceFile:573)
	at dha.render(SourceFile:532)
	at dqn.a(GameRenderer.java:803)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

**Comment by connormcdermid** [comment]
It sounds like there are significantly more characters on a certain line than there are supposed to be (probably Unicode characters or extraneous whitespace)
The only real solution is to delete the book, but if it contains the same contents there should not be a problem.

**Comment by connormcdermid** [comment]
To clarify: these are probably invisible characters added by a bug and/or corruption when the chunk was being saved.

**Comment by 0sp** [comment]
Update: This does not seem to be book-specific. This crash will occasionally happen with any book and quill, named or not, and happens about one in 5 times.

**Comment by 0sp** [comment]
Closing this issue to remake it in a more concise way.
