### ISSUE TITLE
(Update from #24) Reading from an unsigned book and quill will cause a game crash on the client side approximately 20% of the time.

### ISSUE THREAD

**Issue by 0sp** [rDankMemes/Minecraft-Server-Support#25]
**Describe the bug**
When viewing the pages of a book and quill, there is a small but not insignificant chance that your game will crash with an IndexOutOfBounds exception. This has been confirmed to happen with both named and unnamed book and quills (using an anvil), and on client versions 1.15.2, 1.15.1, and 1.14.*. The issue has not been tested with written books, which is the item book and quills become after they are read-only and signed.

**To Reproduce**
1. Create a book and quill.
2. Repeatedly open and close the book.
3. Eventually, your game may crash.

**Expected behavior**
The game should not crash.

**Screenshots**

**Your Environment**
 - Client Version: 1.15.2
 - OS: Mint
 - Mods or Shaders: OptiFine

**Additional context**

Error message:
The game crashed whilst rendering screen
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: [variable number depending on contents of book]

        at java.lang.String.substring(String.java:1951)
	at dha.m(SourceFile:573)
	at dha.render(SourceFile:532)
	at dqn.a(GameRenderer.java:803)
	at dbn.d(SourceFile:989)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

**Comment by jacksonwelsh** [comment]
https://bugs.mojang.com/projects/MC/issues

**Comment by elfahbeht-soop** [comment]
More specifically https://bugs.mojang.com/browse/MC-149792

**Comment by 0sp** [comment]
That bug is with colored text in books, these crashes happen without colored text.
